name: Run scripts

on: [push]

jobs:
  Verify-all-scripts-work:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: |
          npm run lint
      - name: test
        run: |
          npm run test
      - name: "test:cov"
        run: |
          npm run test:cov
      - name: build
        run: |
          npm run build
